# Server
server.port=8080
server.servlet.context-path=/employee-api

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=System@1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=mySecretKeyForEmployeeManagementProject123456789
jwt.expiration=3600000


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE